TALAS: Turret Class Reference
Turret Class Reference
TALAS rotating turret with laser gun.
#include <Turret.h>
Public Member Functions
Turret ()
Constructor.
void attach (uint8_t pinLaser)
Attach turret with laser gun only.
void attach (uint8_t pinLaser, uint8_t pinH, uint8_t pinV)
Attach movable turret with laser gun.
void setRange (uint8_t minH, uint8_t maxH, uint8_t minV, uint8_t maxV)
Set servos angle range.
void setDelta (uint8_t dH, uint8_t dV)
Set servos angle increment/decrement value.
void enable ()
Enable turret.
void disable ()
Disable turret.
void reset ()
Reset turret.
uint8_t getH ()
Get current horizontal position.
uint8_t getV ()
Get current vertical position.
void up ()
Rotate turret up.
void down ()
Rotate turret down.
void left ()
Rotate turret left.
void right ()
Rotate turret right.
void impulse (unsigned long length)
Fire laser gun.
Public Attributes
uint8_t h0
Initial horizontal angle.
uint8_t v0
Initial vertical angle.
Detailed Description
TALAS rotating turret with laser gun.
Member Function Documentation
attach() [1/2]
void Turret::attach (uint8_t pinLaser)
Attach turret with laser gun only.
Parameters
pinLaser pin for laser gun.
Referenced by attach(), and Talas::attachTurret().
attach() [2/2]
void Turret::attach (uint8_t pinLaser, uint8_t pinH, uint8_t pinV)
Attach movable turret with laser gun.
Parameters
pinLaser pin for laser gun.
pinH pin for horizontal servo.
pinV pin for vertical servo.
References attach().
getH()
uint8_t Turret::getH ()
Get current horizontal position.
Returns
Horizontal angle (degrees).
Referenced by Talas::dispatch(), and Talas::slower().
getV()
uint8_t Turret::getV ()
Get current vertical position.
Returns
Vertical angle (degrees).
Referenced by Talas::dispatch(), and Talas::slower().
impulse()
void Turret::impulse (unsigned long length)
Fire laser gun.
Emit a laser impulse with specified length in ms.
Parameters
length impulse length (ms).
Referenced by Talas::fire().
reset()
void Turret::reset ()
Reset turret.
Turn to the initial position.
References h0, and v0.
Referenced by Talas::attachTurret(), Talas::dispatch(), and Talas::slower().
setDelta()
void Turret::setDelta (uint8_t dH, uint8_t dV)
Set servos angle increment/decrement value.
Parameters
dH,dV new increment/decrement values.
Referenced by Talas::slower().
setRange()
void Turret::setRange (uint8_t minH, uint8_t maxH, uint8_t minV, uint8_t maxV)
Set servos angle range.
Parameters
minH,maxH horizontal range.
minV,maxV vertical range.
Referenced by Talas::slower().
The documentation for this class was generated from the following files:
lib/Talas/src/Turret.h
lib/Talas/src/Turret.cpp